### ISSUE TITLE
intra_target_test number

### ISSUE THREAD

**Issue by OceanSnape** [ZurichNLP/xstance#1]
hi， may i have a question? Is the intra_target test de and fr means new_comments_defr？but i find that the number of intra-target_test_de+the number of intra_target_test_fr ！= the number of new_comments_defr.

**Comment by jvamvas** [comment]
Hi @OceanSnape, thank you for pointing this out!
I assume you are referring to Table 2 in the paper? It seems that the "Test" and "Valid" counts are mistakenly swapped in the first column.
The fixed table should look like this:
![image](https://user-images.githubusercontent.com/5830820/111866464-e87ed980-896d-11eb-9a65-61fbee9417f8.png)
